//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registeration___Login_Desktop_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allatribite
    {
        public int user_idd { get; set; }
        public string user_Username { get; set; }
        public string user_Passwordd { get; set; }
        public Nullable<int> user_Age { get; set; }
        public string user_Gender { get; set; }
        public string user_Phonenumber { get; set; }
        public string user_City { get; set; }
    }
}
