//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registeration___Login_Desktop_Application
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Login_Desktop_ApplicationEntities4 : DbContext
    {
        public Login_Desktop_ApplicationEntities4()
            : base("name=Login_Desktop_ApplicationEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adminnn> Adminnns { get; set; }
        public virtual DbSet<Allatribite> Allatribites { get; set; }
    }
}
